# Generated by Django 5.2.8 on 2025-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение проекта'),
        ),
    ]
